"""Create master_admins table

Revision ID: 05ab3ea3e870
Revises: 8c21c993624b
Create Date: 2025-07-07 20:19:33.033691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05ab3ea3e870'
down_revision: Union[str, None] = '8c21c993624b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('master_admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('master_admins', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_master_admins_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_master_admins_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('master_admins', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_master_admins_id'))
        batch_op.drop_index(batch_op.f('ix_master_admins_email'))

    op.drop_table('master_admins')
    # ### end Alembic commands ###
